# Analog application AppID
- mmio:
  - AmcCarrierCore: 
    - AppMps:
      - AppMpsRegBase:
        - mpsAppId: !<value> 125


# Disable all thresholds
- mmio:
  - AmcCarrierCore:
    - AppMps:
      - AppMpsRegAppCh:
        - channel:
          - idleEn: !<value> 0x0
          - lcls1Thr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
          - stdThr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
          - idleThr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
          - altThr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
